from glob import glob
from os.path import basename
# kallisto genome index #
kallindex = "/n/holyscratch01/informatics/adamf/kallisto_snakemake_test/index/Drosophila_melanogaster.BDGP6.dna_sm.toplevel.transcripts.idx"

# fastq directory #
fastqDir = "/n/holyscratch01/informatics/adamf/kallisto_snakemake_test/fastq/"

# fastq suffixes #
r1Suffix = "_1.fastq.gz"
r2Suffix = "_2.fastq.gz"

#output directory #
kallisto_outdir = "/n/holyscratch01/informatics/adamf/kallisto_snakemake_test/kallisto_quants/"


SAMPLES = list(set([basename(i.split('/')[-1].split('_')[0]) for i in glob("%s*gz" % fastqDir)]))
print(SAMPLES)
rule all:
	input:
		expand("%s{sample}_quant" % kallisto_outdir,sample=SAMPLES)

rule kallisto_quant:
	input:
		kallindex=kallindex,
		r1="%s{sample}%s" % (fastqDir,r1Suffix),
		r2="%s{sample}%s" % (fastqDir,r2Suffix),
	output:
		directory("%s{sample}_quant" % kallisto_outdir)

	shell:
		"kallisto quant -i {input.kallindex} -t 6 -b 100 -o {output} {input.r1} {input.r2}"
